### ISSUE TITLE
新增供应商，供应商和库存关联关系。

### ISSUE THREAD

**Issue by githubliwei1986** [lirunwin/inventory-client#1]
在我的客户下面添加一个我的供应商。同时在入库时，需要添加供应商信息。

**Comment by lirunwin** [comment]
供应商和客户属于同级的。客户和供应商没有直接关系。只是库存关联供应商？

**Comment by lirunwin** [comment]
我觉得供应商还是和产品关联哦
和库存关联有点说不通

**Comment by githubliwei1986** [comment]
先有我的产品 再有库存，但是库存里面的同种规格的产品可能来自不同的供应商。
所以我的产品只定义产品本身的属性，产品附加上供应商信息、产地、价格才可以入库。

**Comment by githubliwei1986** [comment]
先有我的产品 再有库存，但是库存里面的同种规格的产品可能来自不同的供应商。
所以我的产品只定义产品本身的属性，产品附加上供应商信息、产地、价格才可以入库。
